version: "3.8"
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: jedi1290
      MYSQL_DATABASE: db-blog
    ports:
      - "3306:3306"  
    volumes:
      - db-blog:/var/lib/mysql

  web:
    depends_on:
      - db
    build: .
    ports:
      - "4000:4000"
    restart: on-failure

volumes: 
  db-blog:    