services:
  db_mysql:
    image: mysql/mysql-server
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
  
  app:
    build: .
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    depends_on:
      - db_mysql
    
